@extends('layouts.dashboard')

@section('content')
<div class="container mx-auto py-10">
    <div class="mb-6">
        <h1 class="text-3xl font-bold">Relieving Letters</h1>
    </div>

    @if(session('success'))
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
            <span class="block sm:inline">{{ session('success') }}</span>
        </div>
    @endif

    <div class="bg-white shadow-md rounded my-6">
        <table class="min-w-full table-auto">
            <thead>
                <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                    <th class="py-3 px-6 text-left">Employee</th>
                    <th class="py-3 px-6 text-left">Letter Date</th>
                    <th class="py-3 px-6 text-left">Status</th>
                    <th class="py-3 px-6 text-left">Generated By</th>
                    <th class="py-3 px-6 text-left">Generated At</th>
                    <th class="py-3 px-6 text-center">Actions</th>
                </tr>
            </thead>
            <tbody class="text-gray-600 text-sm font-light">
                @forelse($letters as $letter)
                    <tr class="border-b border-gray-200 hover:bg-gray-100">
                        <td class="py-3 px-6 text-left whitespace-nowrap">
                            <div class="flex items-center">
                                <span class="font-medium">{{ $letter->resignation->employee->employee_name }}</span>
                            </div>
                        </td>
                        <td class="py-3 px-6 text-left">
                            {{ $letter->letter_date->format('M d, Y') }}
                        </td>
                        <td class="py-3 px-6 text-left">
                            <span class="bg-{{ $letter->status === 'generated' ? 'green' : 'yellow' }}-200 text-{{ $letter->status === 'generated' ? 'green' : 'yellow' }}-600 py-1 px-3 rounded-full text-xs">
                                {{ ucfirst($letter->status) }}
                            </span>
                        </td>
                        <td class="py-3 px-6 text-left">
                            {{ $letter->generatedBy->name }}
                        </td>
                        <td class="py-3 px-6 text-left">
                            {{ $letter->generated_at->format('M d, Y H:i') }}
                        </td>
                        <td class="py-3 px-6 text-center">
                            <div class="flex item-center justify-center space-x-2">
                                <a href="{{ route('relieving_letter.preview', $letter) }}" class="text-blue-500 hover:text-blue-700">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
                                    </svg>
                                </a>
                                <a href="{{ route('relieving_letter.download', $letter) }}" class="text-green-500 hover:text-green-700">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
                                    </svg>
                                </a>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr class="border-b border-gray-200">
                        <td colspan="6" class="py-8 text-center text-gray-500">
                            No relieving letters found
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="mt-4">
        {{ $letters->links() }}
    </div>
</div>
@endsection
